backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use backend\models\Category;
use backend\models\CategoryNews;
use backend\models\City;
use backend\models\Currency;
use backend\models\Multimedia;
use backend\models\News;
use backend\models\Social;
use backend\models\Tag;
//use frontend\models\HtmlParser;
use backend\models\Weather;
use DateTime;
use DOMDocument;
use function GuzzleHttp\Psr7\str;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\db\Exception;
use yii\db\Expression;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\httpclient\Client;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {

        Yii::$app->params["base_currencies"] = Currency::find()->orderBy('order_index')->limit(3)->all();
        Yii::$app->params["base_first_weather"] = Weather::findOne(['city_id'=>1,'date'=>date('Y-m-d')]);
        Yii::$app->params["base_socials"] = Social::find()->orderBy('order_index')->all();
        Yii::$app->params["base_categories"] = Category::find()->where(['status' => 1])->where(['IS', 'parent', null])->orderBy('order_index')->all();
        Yii::$app->params["base_footer_newses"] = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(3)->all();
        Yii::$app->params["base_right_popular_newses"] = News::find()->where(['is_active' => 1])->orderBy(['read_count' => SORT_DESC, 'publish_start_date' => SORT_DESC])->limit(6)->all();
        Yii::$app->params["base_right_recent_newses"] = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(16)->all();
        Yii::$app->params["base_right_random_newses"] = News::find()->where(['is_active' => 1, 'show_slider' => 1])->orderBy(new Expression('rand()'))->limit(6)->all();
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }



    public function beforeAction($action)
    {
        if ($action->id == 'error') {
            $this->layout = 'main_base';
        }

//        $cookies = Yii::$app->response->cookies;
//        $cookies->add(new \yii\web\Cookie([
//            'name' => 'language',
//            'value' => 'az'
//        ]));
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        try{
        $this->layout = 'main_base';
//        $base_categories = Category::find()->where(['status' => 1])->orderBy('order_index')->all();
        $base_slider_newses = News::find()->where(['is_active' => 1, 'show_slider' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(5)->all();
        $context = [
            'base_slider_newses' => $base_slider_newses,
        ];
        return $this->render('index', $context);
        }catch (Exception $exception){
            die(var_dump($exception));
        }
    }

    public function actionAjaxnewsletter(){
        if(Yii::$app->request->isAjax && Yii::$app->request->isGet){
            $message_code = 0;
            $formatter = \Yii::$app->formatter;
            sleep(0.5);
            $content = '';
            $pageNO = Yii::$app->getRequest()->getQueryParam('page');
            $offset_number = 16 + (int)$pageNO*8;
//        $query = News::find()->where(['is_active' => 1, 'category_id' => $category->id])->orderBy(['publish_start_date' => SORT_DESC]);
            $query = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->offset($offset_number)->limit(8)->all();
            $countQuery = count($query);
//            $pages = new Pagination(['totalCount' => $countQuery->count(),'pageSizeLimit'=>[4, 50],  'pageSize' => 5]);
//            $newses = $query->offset(16 )
//
//                ->all();
//            $content = $pageNO . $offset_number;
            foreach ($query as $recent_news){
                $content = $content . '<article class="item clear border-bottom" itemscope itemtype="http://schema.org/NewsArticle">

                        <link itemprop="mainEntityOfPage" href="http://goldnews.az/article-1" />
                    
                        <a href="'.Url::toRoute(['site/news', 'n_id' => $recent_news->u_id, 'n_slug' => $recent_news->slug]).'" title="'.$recent_news->first_name . $recent_news->second_name.'">
                    
                            <div class="thumb hover" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
                                <i class="type xs icon-photo"></i>
                                <img src="'. $recent_news->image . '" alt="alt" width="200" height="200" itemprop="url">
                                <meta itemprop="width" content="200">
                                <meta itemprop="height" content="200">
                            </div>
                    
                            <div class="info">
                    
                                <h3 class="title m-0 m-b-5 tr-3s" itemprop="headline">
                                    <span class="prefix-name">'.$recent_news->first_name.'</span>
                                    <span class="suffix-name">'.$recent_news->second_name.'</span>
                                </h3>
                    
                                <!--                                        <span class="meta-data m-r-10" itemprop="genre" title="Category Name">Category Name</span>-->
                                <time class="meta-data" itemprop="datePublished" datetime="2017-01-15T20:15"><i class="icon-clock"></i> '.$formatter->asDate($recent_news->publish_start_date, 'php: d, F').'</time>
                    
                                <meta itemprop="dateModified" content="2017-01-15T20:15"/>
                                <meta itemprop="author" content="Author">
                                <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                                    <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                                        <meta itemprop="url" content="https://goldnews.az/logo.jpg">
                                        <meta itemprop="width" content="400">
                                        <meta itemprop="height" content="400">
                                    </div>
                                    <meta itemprop="name" content="goldnews.az">
                                </div>
                    
                            </div>
                    
                        </a>
                    </article>';
            }
            $message_code = 1;
            $data = array('message_code' => $message_code, 'content' => $content);
            \Yii::$app->response->format = 'json';
            return $data;
        }else{

        }
    }
    public function actionPage($p_slug)
    {
        $this->layout = 'main_base';
//        $base_categories = Category::find()->where(['status' => 1])->orderBy('order_index')->all();
        if ($p_slug == 'saytda-reklam') {
            $title = 'SAYTDA REKLAM';
            $content = '';
        } else if ($p_slug == 'haqqimizda') {
            $title = 'HAQQIMIZDA';
            $content = '';
        } else {
            $this->layout = 'main_base';
            return $this->render('error');
        }
        $context = [
            'p_slug' => $p_slug,
            'title' => $title,
            'content' => $content,
        ];
        return $this->render('page', $context);
    }

    public function actionCategory($c_slug)
    {
        $this->layout = 'main_base';
        $category = Category::findOne(['slug' => $c_slug]);
        if (empty($category)) {
            $this->layout = 'main_base';
            return $this->render('error');
        }
//        $query = News::find()->where(['is_active' => 1, 'category_id' => $category->id])->orderBy(['publish_start_date' => SORT_DESC]);
        $query = News::find()->where(['category_id' => $category->id])
            ->orderBy(['publish_start_date' => SORT_DESC]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 24]);
        $newses = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
//        die(var_dump($pages));
        $context = [
            'category' => $category,
            'newses' => $newses,
            'pages' => $pages,
        ];
        return $this->render('category', $context);
    }

    public function actionRightnews()
    {
        $message_code = 0;

frontend/views/site/include/_right_bar.php
<?php
/**
 * Created by PhpStorm.
 * User: rahim
 * Date: 7/23/2017
 * Time: 10:29
 */

use yii\helpers\Url;

$formatter = \Yii::$app->formatter;
$base_right_recent_newses = Yii::$app->params["base_right_recent_newses"]

?>
<input type="hidden" value="<?php echo Url::toRoute(['site/ajaxnewsletter']) ?>" id="ajax-newsletter-url">
<aside class="col-md-3 col-sm-12 col-xs-12" data-col="1" itemscope itemtype="http://schema.org/WPSideBar">

    <div class="fixed-wrap">

        <div class="row-10">

            <div class="col-lg-12 col-md-12 col-sm-4 hidden-xs m-b-20">
                <div class="banner-100p shadow">
                    <div class="content flex-center"></div>
                </div>
            </div>

            <div class="col-lg-12 col-md-12 hidden-sm col-xs-12">

                <div class="banner-20p m-b-10 shadow visible-xs">
                    <div class="content flex-center"></div>
                </div>

                <div class="time-line m-b-20 shadow border-bottom clear">

                    <h2 class="content-title m-0 p-15 border-bottom text-uppercase"><i class="icon-newspaper-2"></i> Xəbər lenti</h2>

                    <div class="content scrl">
                        <?php $i=1 ?>
                        <?php foreach ($base_right_recent_newses as $recent_news) { ?>
                            <article class="item clear border-bottom" itemscope itemtype="http://schema.org/NewsArticle">

                                <link itemprop="mainEntityOfPage" href="http://goldnews.az/article-1" />

                                <a href="<?php echo Url::toRoute(['site/news', 'n_id' => $recent_news->u_id, 'n_slug' => $recent_news->slug]); ?>" title="<?= $recent_news->first_name?> <?= $recent_news->second_name?>">

                                    <div class="thumb hover" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
                                        <i class="type xs icon-photo"></i>
                                        <img src="<?= $recent_news->image?>" alt="alt" width="200" height="200" itemprop="url">
                                        <meta itemprop="width" content="200">
                                        <meta itemprop="height" content="200">
                                    </div>

                                    <div class="info">

                                        <h3 class="title m-0 m-b-5 tr-3s" itemprop="headline">
                                            <span class="prefix-name"><?= $recent_news->first_name?></span>
                                            <span class="suffix-name"><?= $recent_news->second_name?></span>
                                        </h3>

<!--                                        <span class="meta-data m-r-10" itemprop="genre" title="Category Name">Category Name</span>-->
                                        <time class="meta-data" itemprop="datePublished" datetime="2017-01-15T<?= $formatter->asDate($recent_news->publish_start_date, 'php: d, F')?>"><i class="icon-clock"></i> <?= $formatter->asDate($recent_news->publish_start_date, 'php: H:s')?></time>

                                        <meta itemprop="dateModified" content="2017-01-15T20:15"/>
                                        <meta itemprop="author" content="Author">
                                        <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                                            <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                                                <meta itemprop="url" content="https://goldnews.az/logo.jpg">
                                                <meta itemprop="width" content="400">
                                                <meta itemprop="height" content="400">
                                            </div>
                                            <meta itemprop="name" content="goldnews.az">
                                        </div>

                                    </div>

                                </a>
                            </article>
                            <?php if ($i==1 or ($i-1)%5==0 or $i==count($base_right_recent_newses)){?>
                                <div class="item border-bottom visible-xs clear">
                                    <div class="banner-20p">
                                        <div class="content flex-center"></div>
                                    </div>
                                </div>
                            <?php }?>
                        <?php $i++?>
                        <?php }?>

                    </div>
                    <a id="scrl-div-loader" style="display: none;" class="item block text-center bg-gray clear">yüklənir....</a>

                </div>

            </div>

            <div class="col-lg-12 col-md-12 col-sm-4 hidden-xs m-b-20">
                <div class="banner-100p shadow">
                    <div class="content flex-center"></div>
                </div>
            </div>

            <div class="col-lg-12 col-md-12 col-sm-4 hidden-xs">
                <div class="banner-100p shadow">
                    <div class="content flex-center"></div>
                </div>
            </div>

        </div>

    </div>

</aside>

frontend/views/site/include/right_bar_part.php
<?php
/**
 * Created by PhpStorm.
 * User: rahim
 * Date: 8/21/2017
 * Time: 12:27
 */

$formatter = \Yii::$app->formatter;

?>

<article class="item clear border-bottom" itemscope itemtype="http://schema.org/NewsArticle">

    <link itemprop="mainEntityOfPage" href="http://goldnews.az/article-1" />

    <a href="<?php echo $formatter->asDate($recent_news->publish_start_date, 'long'); ?>" title="<?= $recent_news->first_name?> <?= $recent_news->second_name?>">

        <div class="thumb hover" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
            <i class="type xs icon-photo"></i>
            <img src="<?= $recent_news->image?>" alt="alt" width="200" height="200" itemprop="url">
            <meta itemprop="width" content="200">
            <meta itemprop="height" content="200">
        </div>

        <div class="info">

            <h3 class="title m-0 m-b-5 tr-3s" itemprop="headline">
                <span class="prefix-name"><?= $recent_news->first_name?></span>
                <span class="suffix-name"><?= $recent_news->second_name?></span>
            </h3>

            <!--                                        <span class="meta-data m-r-10" itemprop="genre" title="Category Name">Category Name</span>-->
            <time class="meta-data" itemprop="datePublished" datetime="2017-01-15T20:15"><i class="icon-clock"></i> 20:15</time>

            <meta itemprop="dateModified" content="2017-01-15T20:15"/>
            <meta itemprop="author" content="Author">
            <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                    <meta itemprop="url" content="https://goldnews.az/logo.jpg">
                    <meta itemprop="width" content="400">
                    <meta itemprop="height" content="400">
                </div>
                <meta itemprop="name" content="goldnews.az">
            </div>

        </div>

    </a>
</article>