backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use backend\models\Category;
use backend\models\CategoryNews;
use backend\models\City;
use backend\models\Currency;
use backend\models\Multimedia;
use backend\models\News;
use backend\models\Social;
use backend\models\Tag;
//use frontend\models\HtmlParser;
use backend\models\Weather;
use DateTime;
use DOMDocument;
use function GuzzleHttp\Psr7\str;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\db\Exception;
use yii\db\Expression;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\httpclient\Client;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {

        Yii::$app->params["base_currencies"] = Currency::find()->orderBy('order_index')->limit(3)->all();
        Yii::$app->params["base_first_weather"] = Weather::findOne(['city_id'=>1,'date'=>date('Y-m-d')]);
        Yii::$app->params["base_socials"] = Social::find()->orderBy('order_index')->all();
        Yii::$app->params["base_categories"] = Category::find()->where(['status' => 1])->where(['IS', 'parent', null])->orderBy('order_index')->all();
        Yii::$app->params["base_footer_newses"] = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(3)->all();
        Yii::$app->params["base_right_popular_newses"] = News::find()->where(['is_active' => 1])->orderBy(['read_count' => SORT_DESC, 'publish_start_date' => SORT_DESC])->limit(6)->all();
        Yii::$app->params["base_right_recent_newses"] = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(16)->all();
        Yii::$app->params["base_right_random_newses"] = News::find()->where(['is_active' => 1, 'show_slider' => 1])->orderBy(new Expression('rand()'))->limit(6)->all();
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }



    public function beforeAction($action)
    {
        if ($action->id == 'error') {
            $this->layout = 'main_base';
        }

//        $cookies = Yii::$app->response->cookies;
//        $cookies->add(new \yii\web\Cookie([
//            'name' => 'language',
//            'value' => 'az'
//        ]));
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        try{
        $this->layout = 'main_base';
//        $base_categories = Category::find()->where(['status' => 1])->orderBy('order_index')->all();
        $base_slider_newses = News::find()->where(['is_active' => 1, 'show_slider' => 1])->orderBy(['publish_start_date' => SORT_DESC])->limit(5)->all();
        $context = [
            'base_slider_newses' => $base_slider_newses,
        ];
        return $this->render('index', $context);
        }catch (Exception $exception){
            die(var_dump($exception));
        }
    }

    public function actionAjaxnewsletter(){
        if(Yii::$app->request->isAjax && Yii::$app->request->isGet){
            $message_code = 0;
            $formatter = \Yii::$app->formatter;
            sleep(0.5);
            $content = '';
            $pageNO = Yii::$app->getRequest()->getQueryParam('page');
            $offset_number = 16 + (int)$pageNO*8;
//        $query = News::find()->where(['is_active' => 1, 'category_id' => $category->id])->orderBy(['publish_start_date' => SORT_DESC]);
            $query = News::find()->where(['is_active' => 1])->orderBy(['publish_start_date' => SORT_DESC])->offset($offset_number)->limit(8)->all();
            $countQuery = count($query);
//            $pages = new Pagination(['totalCount' => $countQuery->count(),'pageSizeLimit'=>[4, 50],  'pageSize' => 5]);
//            $newses = $query->offset(16 )
//
//                ->all();
//            $content = $pageNO . $offset_number;
            foreach ($query as $recent_news){
                $content = $content . '<article class="item clear border-bottom" itemscope itemtype="http://schema.org/NewsArticle">

                        <link itemprop="mainEntityOfPage" href="http://goldnews.az/article-1" />
                    
                        <a href="'.Url::toRoute(['site/news', 'n_id' => $recent_news->u_id, 'n_slug' => $recent_news->slug]).'" title="'.$recent_news->first_name . $recent_news->second_name.'">
                    
                            <div class="thumb hover" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
                                <i class="type xs icon-photo"></i>
                                <img src="'. $recent_news->image . '" alt="alt" width="200" height="200" itemprop="url">
                                <meta itemprop="width" content="200">
                                <meta itemprop="height" content="200">
                            </div>
                    
                            <div class="info">
                    
                                <h3 class="title m-0 m-b-5 tr-3s" itemprop="headline">
                                    <span class="prefix-name">'.$recent_news->first_name.'</span>
                                    <span class="suffix-name">'.$recent_news->second_name.'</span>
                                </h3>
                    
                                <!--                                        <span class="meta-data m-r-10" itemprop="genre" title="Category Name">Category Name</span>-->
                                <time class="meta-data" itemprop="datePublished" datetime="2017-01-15T20:15"><i class="icon-clock"></i> '.$formatter->asDate($recent_news->publish_start_date, 'php: d, F').'</time>
                    
                                <meta itemprop="dateModified" content="2017-01-15T20:15"/>
                                <meta itemprop="author" content="Author">
                                <div itemprop="publisher" itemscope itemtype="https://schema.org/Organization">
                                    <div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject">
                                        <meta itemprop="url" content="https://goldnews.az/logo.jpg">
                                        <meta itemprop="width" content="400">
                                        <meta itemprop="height" content="400">
                                    </div>
                                    <meta itemprop="name" content="goldnews.az">
                                </div>
                    
                            </div>
                    
                        </a>
                    </article>';
            }
            $message_code = 1;
            $data = array('message_code' => $message_code, 'content' => $content);
            \Yii::$app->response->format = 'json';
            return $data;
        }else{

        }
    }
    public function actionPage($p_slug)
    {
        $this->layout = 'main_base';
//        $base_categories = Category::find()->where(['status' => 1])->orderBy('order_index')->all();
        if ($p_slug == 'saytda-reklam') {
            $title = 'SAYTDA REKLAM';
            $content = '';
        } else if ($p_slug == 'haqqimizda') {
            $title = 'HAQQIMIZDA';
            $content = '';
        } else {
            $this->layout = 'main_base';
            return $this->render('error');
        }
        $context = [
            'p_slug' => $p_slug,
            'title' => $title,
            'content' => $content,
        ];
        return $this->render('page', $context);
    }

    public function actionCategory($c_slug)
    {
        $this->layout = 'main_base';
        $category = Category::findOne(['slug' => $c_slug]);
        if (empty($category)) {
            $this->layout = 'main_base';
            return $this->render('error');
        }
//        $query = News::find()->where(['is_active' => 1, 'category_id' => $category->id])->orderBy(['publish_start_date' => SORT_DESC]);
        $query = News::find()->where(['category_id' => $category->id])
            ->orderBy(['publish_start_date' => SORT_DESC]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 24]);
        $newses = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
//        die(var_dump($pages));
        $context = [
            'category' => $category,
            'newses' => $newses,
            'pages' => $pages,
        ];
        return $this->render('category', $context);
    }

    public function actionRightnews()
    {
        $message_code = 0;

frontend/views/site/currency.php
<?php
/**
 * Created by PhpStorm.
 * User: rahim
 * Date: 8/15/2017
 * Time: 1:20
 */

use yii\helpers\Url;

$this->title = 'Valyuta';
$this->registerMetaTag([
    'property' => 'og:url',
    'content' => Url::toRoute(['site/currency']),
]);
$this->registerMetaTag([
    'property' => 'og:title',
    'content' => 'Valyuta',
]);

$this->registerMetaTag([
    'property' => 'og:image',
    'content' => 'static/main-base/assets/images/logos/gold_news.png',
]);


$formatter = \Yii::$app->formatter;
?>
<div class="page-wrapper">

    <div class="container p-l-20 p-r-20">

        <div class="row-15">

            <div class="main-side col-md-12 col-sm-12 col-xs-12">

                <div class="static-pages m-t-20">

                    <nav class="bg-white shadow p-15 m-b-20">

                        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                                <a href="index.php" title="goldnews.az - Ana səhifə" itemprop="item">
                                    <span itemprop="name">Ana səhifə</span>
                                </a>
                                <meta itemprop="position" content="1">
                            </li>
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                                <a href="category.php" title="Valyuta" itemprop="item">
                                    <span itemprop="name">Valyuta</span>
                                </a>
                                <meta itemprop="position" content="2">
                            </li>
                        </ol>

                    </nav>

                    <div class="row-10">

                        <div class="col-md-3 col-sm-12 col-xs-12 m-b-20">

                            <div class="static-side-menu shadow bg-white p-t-10 p-b-10 clear">

                                <a href="<?php echo Url::toRoute(['site/page', 'p_slug' => 'haqqimizda']) ?>" class="tr-3s"><i class="icon-info-circle-thin"></i> Haqqımızda</a>
                                <!--                                <a href="contact.php" class="tr-3s"><i class="icon-envelope-o"></i> Bizimlə əlaqə</a>-->
                                <a href="<?php echo Url::toRoute(['site/page', 'p_slug' => 'saytda-reklam']) ?>" class="tr-3s "><i class="icon-ads"></i> Saytda reklam</a>
                                <a href="<?php echo Url::toRoute(['site/weather']) ?>" class="tr-3s"><i class="wi wi-day-cloudy"></i> Hava</a>
                                <a href="<?php echo Url::toRoute(['site/currency']) ?>" class="tr-3s current-page"><i class="icon-currency-azn"></i> Valyuta</a>

                            </div>

                        </div>

                        <div class="col-md-9 col-sm-12 col-xs-12 m-b-20">

                            <div class="static-page-wrapper shadow bg-white clear">

                                <h1 class="content-title p-20 m-0 border-bottom"><strong><i
                                                class="icon-currency-azn"></i> VALYUTA</strong></h1>

                                <div class="currency">

<!--                                    <div class="convertor p-20 bg-gray">-->
<!---->
<!--                                        <div class="row-7">-->
<!---->
<!--                                            <div class="col-md-3 col-sm-3 col-xs-6">-->
<!--                                                <label>Məbləğ</label>-->
<!--                                                <input type="text" class="input" placeholder="məs: 200">-->
<!--                                            </div>-->
<!---->
<!--                                            <div class="col-md-3 col-sm-3 col-xs-6">-->
<!--                                                <label>Valyutadan</label>-->
<!--                                                <select class="input">-->
<!--                                                    <option value="azn">AZN</option>-->
<!--                                                    <option value="rub">RUB</option>-->
<!--                                                    <option value="gbp">GBP</option>-->
<!--                                                    <option value="eur">EUR</option>-->
<!--                                                    <option value="ytl">YTL</option>-->
<!--                                                </select>-->
<!--                                            </div>-->
<!---->
<!--                                            <div class="clear m-b-10 visible-xs"></div>-->
<!---->
<!--                                            <div class="col-md-3 col-sm-3 col-xs-6">-->
<!--                                                <label>Valyutaya</label>-->
<!--                                                <select class="input">-->
<!--                                                    <option value="azn">AZN</option>-->
<!--                                                    <option value="rub">RUB</option>-->
<!--                                                    <option value="gbp">GBP</option>-->
<!--                                                    <option value="eur">EUR</option>-->
<!--                                                    <option value="ytl">YTL</option>-->
<!--                                                </select>-->
<!--                                            </div>-->
<!---->
<!--                                            <div class="col-md-3 col-sm-3 col-xs-6">-->
<!--                                                <label>Nəticə</label>-->
<!--                                                <input type="text" class="input" placeholder="0,00" readonly>-->
<!--                                            </div>-->
<!---->
<!--                                        </div>-->
<!---->
<!--                                    </div>-->

                                    <div class="clear p-20">

                                        <h4 class="m-t-0 m-b-20"><b>AZN məzənnələri</b>
                                            <smal class="float-right"><?= date('d.m.Y')?></smal>
                                        </h4>

                                        <div class="table-responsive">
                                            <table class="table table-bordered table-hover">

                                                <thead>

                                                <tr>
                                                    <th colspan="2">Valyuta</th>
                                                    <th>Satış</th>
                                                    <th>Status</th>
                                                </tr>

                                                </thead>

                                                <tbody>
                                                <?php foreach ($currencies as $currency) { ?>
                                                    <tr>
                                                        <td><?= $currency->nominal?></td>
                                                        <td><b><?= $currency->name?></b></td>
                                                        <td><?= $currency->value?></td>
                                                        <td><i class="<?php if($currency->status==1){?>up<?php }else if($currency->status==2){?>down<?php }else if($currency->status==0){?>middle<?php }?>">
                                                                <?php if($currency->status==1){?>▲<?php }else if($currency->status==2){?>▼<?php }else if($currency->status==0){?>●<?php }?>
                                                            </i>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                                </tbody>

                                            </table>
                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = '404';
$this->registerMetaTag([
    'property' => 'og:title',
    'content' => '404',
]);

$this->registerMetaTag([
    'property' => 'og:image',
    'content' => 'static/main-base/assets/images/logos/gold_news.png'
]);

?>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-8 col-md-offset-4 col-sm-offset-4 wrong-page wow fadeInDown animated">
            <div class="text-center">
                <h1>We are sorry</h1>
                <p>Unfortunately, the page you were looking for could not be found. It may be temporarily unavailable, moved or no longer exists</p>
            </div>
            <div class="text-center"><span class="ion-sad wrong-icon "></span></div>
            <div class="text-center"><a class="btn btn-danger"  href="index.html">Go to home page</a></div>
        </div>
    </div>
</div>

frontend/views/site/weather.php
<?php
/**
 * Created by PhpStorm.
 * User: rahim
 * Date: 8/15/2017
 * Time: 1:21
 */

use yii\helpers\Url;

$this->title = 'Hava';
$this->registerMetaTag([
    'property' => 'og:url',
    'content' => Url::toRoute(['site/weather']),
]);
$this->registerMetaTag([
    'property' => 'og:title',
    'content' => 'Hava',
]);

$this->registerMetaTag([
    'property' => 'og:image',
    'content' => 'static/main-base/assets/images/logos/gold_news.png',
]);

$formatter = \Yii::$app->formatter;
?>
<div class="page-wrapper">

    <div class="container p-l-20 p-r-20">

        <div class="row-15">

            <div class="main-side col-md-12 col-sm-12 col-xs-12">

                <div class="static-pages m-t-20">

                    <nav class="bg-white shadow p-15 m-b-20">

                        <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                                <a href="index.php" title="goldnews.az - Ana səhifə" itemprop="item">
                                    <span itemprop="name">Ana səhifə</span>
                                </a>
                                <meta itemprop="position" content="1">
                            </li>
                            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                                <a href="category.php" title="Hava" itemprop="item">
                                    <span itemprop="name">Hava</span>
                                </a>
                                <meta itemprop="position" content="2">
                            </li>
                        </ol>

                    </nav>

                    <div class="row-10">

                        <div class="col-md-3 col-sm-12 col-xs-12 m-b-20">

                            <div class="static-side-menu shadow bg-white p-t-10 p-b-10 clear">

                                <a href="<?php echo Url::toRoute(['site/page', 'p_slug' => 'haqqimizda']) ?>"
                                   class="tr-3s"><i class="icon-info-circle-thin"></i> Haqqımızda</a>
                                <!--                                <a href="contact.php" class="tr-3s"><i class="icon-envelope-o"></i> Bizimlə əlaqə</a>-->
                                <a href="<?php echo Url::toRoute(['site/page', 'p_slug' => 'saytda-reklam']) ?>"
                                   class="tr-3s "><i class="icon-ads"></i> Saytda reklam</a>
                                <a href="<?php echo Url::toRoute(['site/weather']) ?>" class="tr-3s current-page"><i
                                            class="wi wi-day-cloudy"></i> Hava</a>
                                <a href="<?php echo Url::toRoute(['site/currency']) ?>" class="tr-3s"><i
                                            class="icon-currency-azn"></i> Valyuta</a>

                            </div>

                        </div>

                        <div class="col-md-9 col-sm-12 col-xs-12 m-b-20">

                            <div class="static-page-wrapper shadow bg-white clear">

                                <h1 class="content-title p-20 m-0 border-bottom"><strong><i
                                                class="wi wi-day-cloudy"></i> HAVA PROQNOZU</strong></h1>

                                <div class="weather">

                                    <div class="header relative"
                                         style="background-image: url(http://www.travelwings.com/special-offers/images/Baku-1.jpg)">

                                        <div class="days row-0">
                                            <?php $i = 1 ?>
                                            <?php foreach ($first_weathers as $first_weather) { ?>
                                                <?php $degrees = explode("/", $first_weather->degrees );?>
                                                <?php if ($i == 1) { ?>

                                                    <div class="day cunnet-day col-md-5 col-sm-5 col-xs-12">
                                                        <div class="day-name p-10">
                                                            <?= $formatter->asDate($first_weather->date, 'php: l')?>
                                                        </div>
                                                        <div class="info-weather p-30">

                                                            <label class="city-name">Bakı</label>

                                                            <h2 class="deg"><b> <?= $degrees[1]?> <sup>o</sup>C</b> <i
                                                                        class="wi wi-day-cloudy"></i></h2>

                                                            <span class="m-r-15"><i class="wi wi-moonrise"></i>  <?= $degrees[0]?>  <sup>o</sup>C</span>
                                                            <span class="m-r-15"><i class="wi wi-strong-wind"></i> <?= $first_weather->wind_speed ?> m/s</span>
                                                            <span><i class="wi wi-humidity"></i> <?= $first_weather->moisture ?>%</span>

                                                        </div>

                                                    </div>
                                                <?php } ?>
                                                <?php if ($i >= 2 and $i <= 7) { ?>
                                                    <?php if ($i == 2) { ?>
                                                        <div class="col-md-7 col-sm-7 col-xs-12">

                                                        <div class="row-0">
                                                    <?php } ?>
                                                    <div class="day next-day col-md-2 col-sm-2 col-xs-4">

                                                        <div class="day-name p-10 text-center"><?= $formatter->asDate($first_weather->date, 'php: l')?></div>

                                                        <div class="info-weather flex-center">

                                                            <span class="icon m-b-20"><i
                                                                        class="wi wi-day-cloudy"></i></span>

                                                            <strong class="deg m-b-20"><b><?= $degrees[0]?><sup>o</sup>C</b></strong>

                                                            <span><i class="wi wi-moonrise"></i> <?= $degrees[1]?> <sup>o</sup>C</span>

                                                        </div>

                                                    </div>
                                                    <?php if ($i == 7) { ?>
                                                        </div>

                                                        </div>
                                                    <?php } ?>
                                                <?php } ?>
                                                <?php $i++ ?>
                                            <?php } ?>


                                        </div>

                                    </div>

                                    <div class="clear p-20">

                                        <h4 class="m-t-0 m-b-20"><b>Digər şəhərlər</b></h4>

                                        <div class="table-responsive">
                                            <table class="table table-bordered table-hover">

                                                <thead>

                                                <tr>
                                                    <th>Şəhər</th>
                                                    <th>Atmosfer hadisələri</th>
                                                    <th>Temperatur <sup>o</sup>C</th>
                                                    <th>Külək m/s</th>
                                                    <th>Rütubət %</th>
                                                </tr>

                                                </thead>

                                                <tbody>
                                                <?php foreach ($weathers as $weather) { ?>
                                                    <tr>
                                                        <td><a href="#"><b><?= $weather->city->name ?></b></a></td>
                                                        <td><i class="wi wi-day-cloudy"></i> <?= $weather->status ?>
                                                        </td>
                                                        <td><b><?= $weather->degrees ?></b></td>
                                                        <td>
                                                            <i class="wi wi-strong-wind"></i> <?= $weather->wind_speed ?>
                                                        </td>
                                                        <td><?= $weather->moisture ?></td>
                                                    </tr>
                                                <?php } ?>
                                                </tbody>

                                            </table>
                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>